### PR TITLE
Solving the type error issue

### PR DESCRIPTION
**Pull request by SWARAJkumar**
solves the problem raised in the issue TypeError: data type "c1" not understood #11  

Changes made to the **common notebook** in particular and also removed axisbg from subplot functions. The code is able to run with python2.7

### CODE REVIEW

**Comment by nmsutton** [comment]
@SWARAJkumar Thanks again for your efforts but I have reviewed the proposed pull request and don’t see that it adds to the project since I already fixed the mentioned issue. Your code removes axisbg from the subplot functions and that seems not needed because the software runs fine with that included. I think there was a misunderstanding because the mentioned issue was never closed while I waited for a response from the original poster. If that is the case, my apologies. I will close this pull request in 5 days if I do not hear back. It should be said that we do appreciate you trying to add to the project in any case though.

**Comment by SWARAJkumar** [comment]
@nmsutton  sorry for the late reply, the dtype='c1, (5,3)u1' in common.ipynb wasn't working, I made a slight change in dtype. If possible just take a look at that part. I tried solving this issue as it was open. But I have tried running the updated code and was still facing issues with the dtype

**Comment by nmsutton** [comment]
@SWARAJkumar No worries about the response time. In the latest dictionary.py file the line ‘dictionary = zeros(26, dtype='c1, (5,3)u1')’ had been removed as part of the fixes I made for the solution to [issue 11](https://github.com/tartavull/snn-rl/issues/11). You are right that common.ipynb includes the non-fixed dictionary.py code and could be updated but that should not be used for running the project, only for explanations with notebooks. You stated that you are still facing issues with the dtype when running the code but I want to confirm with you, are you using the code that no longer contains the dtype ‘c1’ reference in the latest [dictionary.py file](https://github.com/tartavull/snn-rl/blob/master/furtherFormulas/dictionary.py)? If so, can you please clone and run a copy of the latest code and paste the exact error message you are getting?

**Comment by nmsutton** [comment]
@SWARAJkumar I haven’t heard back in a week. Thanks again for your efforts but if I hear no response within 5 days I will close this request.

**Comment by nmsutton** [comment]
@SWARAJkumar I have now copied over the dictionary.py code I previously fixed (to avoid the error you are describing) into [common.ipynb](https://github.com/tartavull/snn-rl/blob/master/notebooks/common.ipynb). I tested it and it should no longer generate the error you have reported. Can you please download the updated [common.ipynb](https://github.com/tartavull/snn-rl/blob/master/notebooks/common.ipynb) code, try it again, and report if there are no more issues? I have tested it on my side and it appears to work, it contains a different way to code the numpy matrix to avoid the error. As before please respond within 5 days to avoid me closing the request.

For clarification, the notebook code you are working with is not the main project’s code. Thank you for helping me see the main project’s readme file did not explain that clearly enough. I have updated the readme’s getting started section to explain how to work with the main code. Also, I added that notebook code is only for explanatory purposes, may be out of date with the main code, and should not be used for the main code. If you try to run the main project code it should have no issues (including the one you specifically mentioned) but I understand you are trying to get the notebook code running instead.

**Comment by nmsutton** [comment]
@SWARAJkumar You’re welcome. Glad to hear the code ran fine. Thank you for the compliments! I appreciate your efforts as well! 

Due to no further issues remaining I am closing this request.

**Pull request closed without merging**
